package com.example.authservice.exception;

public interface AuthServiceMessageCode {

  // Auth
  String USERNAME_NOT_NULL = "0022";
  String PASSWORD_NOT_NULL = "0023";
  String USERNAME_INCORRECT = "0000";
  String USERNAME_OR_PASS_INCORRECT = "0000";
  String USER_INVALID = "0001";

  String UN_AUTHORIZED = "0002";
  String USER_DELETED = "0003";

  // Group
  String GROUP_DUPLICATE = "0004";
  String USER_NOT_FOUND = "0005";
  String ROLE_NOT_FOUND = "0006";
  String ID_NOT_NULL = "0007";
  String GROUP_NOT_FOUND = "0008";
  String GROUP_CODE_CANNOT_MODIFY = "0009";
  String USER_NOT_EXIST_IN_GROUP = "0010";
  String ROLE_NOT_EXIST_IN_GROUP = "0011";
  String ROLE_EXIST_IN_GROUP = "0012";
  String USER_EXIST_IN_GROUP = "0013";

  // Role
  String USER_NOT_EXIST = "0014";
  String ROLE_ALREADY_EXIST = "0015";
  String PERMISSION_NOT_NULL = "0016";
  String PERMISSION_NOT_EXIST = "0017";
  String ROLE_NOT_EXIST = "0018";
  String ROLE_CODE_CANNOT_MODIFY = "0019";

  // User
  String USER_ALREADY_EXIST = "0020";
  String EMAIL_ALREADY_EXIST = "0021";


  String PASSWORD_CONFIRM_NOT_NULL = "0024";
  String PASSWORD_CONFIRM_NOT_MATCH_PASSWORD = "0025";
  String EMAIL_NOT_NULL = "0026";

  String SORT_INVALID = "0027";


  // AUTH
  String CLIENT_INVALID = "0030";
  String API_KEY_INVALID = "0031";
  String CLIENT_ID_INVALID = "0032";
  String CLIENT_SECRET_INVALID = "0033";
  String CLIENT_ALREADY_EXIST = "0034";
  String CLIENT_NOT_EXIST = "0035";
  String CLIENT_AUTH_TYPE_NOT_NULL = "0037";
  String REFRESH_TOKEN_INVALID = "0038";
  String REFRESH_TOKEN_NOT_FOUND = "0039";
  String REFRESH_TOKEN_UN_APPROVED = "0040";
  String REFRESH_TOKEN_EXPIRED = "0041";
  String CLIENT_NAME_NOT_NULL = "0042";
  String IP_INVALID = "0043";

  String DECRYPT_PASSWORD_ERROR = "0044";
  String CLIENT_DEACTIVED = "0045";
  String TOKEN_STATUS_INVALID = "0046";
  String TOKEN_ALREADY_EXIST = "0047";
  String API_KEY_AND_CLIENT_NOT_MATCH = "0048";

  String JWT_NOT_EXIST = "0049";
  String JWT_INVALID = "0050";
  String PASSWORD_INCORRECT = "0051";
  String NEW_PASSWORD_INVALID = "0052";
  String NEW_PASSWORD_CONFIRM_INVALID = "0053";
  String DECRYPT_ERROR = "0054";

  // app
  String APP_ID_NULL = "0054";
  String APP_NOT_FOUND = "0055";

  String USER_NOT_EXIST_IN_APP = "0056";
  String ROLE_INVALID = "0057";

  String OPERATION_NOT_IMPLEMENT = "0058";

  String ID_ACCESS_TOKEN_NULL = "0059";

  String ACCESS_TOKEN_NOT_FOUND = "0060";

  String USER_DEACTIVE = "0061";

  String SERVICE_INVALID = "0062";
  String SERVICE_ALREADY_EXIST = "0063";
  String SERVICE_NOT_FOUND = "0064";

  String FROM_DATE_GREATER_TO_DATE = "0065";

  String FROM_DATE_GREATER_CURRENT_DATE = "0066";

  String TO_DATE_GREATER_CURRENT_DATE = "0067";

  String ID_REQUEST_LOG_NULL = "0068";

  String ROLE_LIST_NOT_NULL = "0068";

  String SYSTEM_ID_NULL = "0069";

  String SYSTEM_NOT_FOUND = "0070";

  String TAG_NOT_FOUND = "0071";
  String API_ID_NOT_NULL = "0072";
  String PURPOSE_NOT_NULL = "0073";
  String API_INVALID = "0074";
  String API_NOT_FOUND = "0075";

  String CODE_SERVICE_NULL = "0076";

  String CODE_EXISTS = "0077";

  String API_ALREADY_EXIST = "0078";

  String ID_SERVICE_NULL = "0079";

  String API_REQUEST_NOT_FOUND = "0080";
  String ACCESS_TOKEN_INVALID = "0081";

  String TOKEN_NULL = "0082";
  String TOKEN_NOT_FOUND = "0083";
  String JWT_NOT_FOUND = "0084";
  String LOG_REQUEST_INVALID = "0085";

  String CLIENT_AUTH_TYPE_INVALID = "0086";

  String CLIENT_API_KEY_INVALID = "0087";
  String CLIENT_API_KEY_NOT_FOUND = "0088";
  String CLIENT_API_KEY_IS_ACTIVE = "0089";
  String CLIENT_API_KEY_EXPIRED = "0090";

  String ROLE_TYPE_NOT_NULL = "0091";
  String ROLE_TYPE_NOT_FOUND = "0092";

  String MISSING_HEADER = "0093";
}
